---
title: "Looping"
author: "Jessica Jagdeo"
date: "2/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

For loop examples in class February 26, 2020:

```{r}

# Calculate the mean of a generated speeds dataframe using a for loop and check with mean(speeds):

speeds = runif(min = 0, max = 100, n = 30)

sum_speeds = 0

for (j in 1:length(speeds)) {
  
  sum_speeds = sum_speeds + speeds[j]
  
}

sum_speeds/length(speeds)

```

```{r}

## Class example: accumulate pollutant until a threshold - how many years does it take

# initial conditions

yr=1

pollutant_level = 5

# loop: set yrs to 10 to ensure that while() does not run forever == to break the loop

while ((pollutant_level < 30) && (yr < 10))   { 
  
  # increase pollutant
pollutant_level = pollutant_level + 0.01* pollutant_level 

# keep track of time
yr = yr + 1

}

pollutant_level

```

```{r}

## Class example: computing net present value of data frame with different damages and discount rates

compute_NPV(20, discount=0.01, time=20)


#generate some input

damages = c(25,33,91,24)

# sensitivity to discount rate

discount_rates = seq(from=0.01, to=0.04, by=0.005)

yr=10

# compute some npv's for different discount rates

# first generate a dataframe to store results

npvs = as.data.frame(matrix(nrow=length(damages), ncol=length(discount_rates)))

# now use a for loop to populate

 for (i in 1:length(damages)) {
   
         for (j in 1:length(discount_rates)) {
           
       npvs[i,j]= compute_NPV(value=damages[i],      
                              
                              discount=discount_rates[j],time=yr )

         }
 }

 npvs

```

```{r}

# My example: calculate runoff ratio with generated precipitation and runoff data

nsample = 30

precip = as.data.frame(rnorm(mean = 50, sd = 10.5, n = nsample))

runoff = as.data.frame(rnorm(mean = 10, sd = 2.5, n = nsample))

for (i in 1:length(precip)) {
  ratio = runoff/precip
}

ratio

#runoff_ratio <- combine(runoff, precip, ratio)

```

